FROM webdevops/php-nginx:debian-8
MAINTAINER Marcel M. Otte <qwc+docker@mmo.to>

ADD https://github.com/Poil/CGraphz/archive/v2.46.2.tar.gz /app/

RUN cd /app && tar xvzf v2.46.2.tar.gz && mv CGraphz-2.46.2 cgraphz
